#print-out-distribution.yaml
---
- name: print out distribution
  hosts: localhost
  gather_facts: True
  tasks:
    - name: "print output"
      debug:
       msg: |
            ansible_distribution: {{ ansible_os_family }}
            ansible_distribution: {{ ansible_distribution }}
            ansible_distribution_version: {{ ansible_distribution_version }}
            ansible_distribution_major_version: {{ ansible_distribution_major_version }}
            ansible_distribution_release: {{ ansible_distribution_release }}
