#test-multiple-and-conditionnals.yaml
---
- name: "and conditionnals"
  hosts: localhost
  gather_facts: True
  tasks:
    - name: "Test two conditions in one line"
      debug:
        msg: "{{ ansible_hostname }} CentOS 8"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    - name: "Test two conditions in two lines"
      debug:
        msg: "{{ ansible_hostname }} CentOS 8"
      when: ansible_distribution == "CentOS" and
            ansible_distribution_major_version == "8"
    - name: "Test multiple conditions in a list"
      debug:
        msg: "{{ ansible_hostname }} CentOS 8"
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "8"
